"""empty message

Revision ID: 2fd6c3c16481
Revises: 
Create Date: 2024-12-01 20:22:20.148494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd6c3c16481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_website', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.String(length=500), nullable=True),
    sa.Column('business_industry', sa.String(length=255), nullable=True),
    sa.Column('business_category', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id_1', sa.Integer(), nullable=False),
    sa.Column('business_id_2', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=255), nullable=True),
    sa.Column('connection_status', sa.String(length=255), nullable=True),
    sa.Column('connection_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['business_id_1'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id_2'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_live', sa.Boolean(), nullable=False),
    sa.Column('service_industry', sa.String(length=255), nullable=True),
    sa.Column('service_description', sa.String(length=500), nullable=True),
    sa.Column('service_type', sa.String(length=255), nullable=True),
    sa.Column('service_tags', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('connections')
    op.drop_table('businesses')
    op.drop_table('users')
    # ### end Alembic commands ###
