"""empty message

Revision ID: 396e6d4dcad7
Revises: 
Create Date: 2024-11-29 19:15:28.309661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396e6d4dcad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_website', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.String(length=500), nullable=True),
    sa.Column('business_industry', sa.String(length=255), nullable=True),
    sa.Column('business_category', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businesses')
    op.drop_table('users')
    # ### end Alembic commands ###
