"""empty message

Revision ID: 58854601afa4
Revises: a2b55ddcc456
Create Date: 2024-11-30 22:22:56.005636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58854601afa4'
down_revision = 'a2b55ddcc456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id_1', sa.Integer(), nullable=False),
    sa.Column('business_id_2', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=255), nullable=True),
    sa.Column('connection_status', sa.String(length=255), nullable=True),
    sa.Column('connection_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['business_id_1'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id_2'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_description', sa.String(length=500), nullable=True),
    sa.Column('service_type', sa.String(length=255), nullable=True),
    sa.Column('service_tags', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('connections')
    # ### end Alembic commands ###
